/*
XENDIT SDK openapi spec_test

Testing CustomerApiService

*/

// Code generated by OpenAPI Generator

package xendit

import (
	"context"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	xendit "github.com/xendit/xendit-go/v3"
)

func Test_xendit_CustomerApiService(t *testing.T) {

	apiKey := os.Getenv("XND_APIKEY")
	if apiKey == "" {
		t.Skip("XND_APIKEY not set")
	}
	
	apiClient := xendit.NewClient(apiKey)

	t.Run("Test CustomerApiService CreateCustomer", func(t *testing.T) {

		resp, httpRes, err := apiClient.CustomerApi.CreateCustomer(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomerApiService GetCustomer", func(t *testing.T) {

		var id string

		resp, httpRes, err := apiClient.CustomerApi.GetCustomer(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomerApiService GetCustomerByReferenceID", func(t *testing.T) {

		resp, httpRes, err := apiClient.CustomerApi.GetCustomerByReferenceID(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomerApiService UpdateCustomer", func(t *testing.T) {

		var id string

		resp, httpRes, err := apiClient.CustomerApi.UpdateCustomer(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
