/*
Refund Service_test

Testing RefundApiService

*/

// Code generated by OpenAPI Generator

package xendit

import (
	"context"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	xendit "github.com/xendit/xendit-go/v3"
)

func Test_xendit_RefundApiService(t *testing.T) {

	apiKey := os.Getenv("XND_APIKEY")
	if apiKey == "" {
		t.Skip("XND_APIKEY not set")
	}
	
	apiClient := xendit.NewClient(apiKey)

	t.Run("Test RefundApiService CreateRefund", func(t *testing.T) {

		resp, httpRes, err := apiClient.RefundApi.CreateRefund(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RefundApiService GetRefund", func(t *testing.T) {

		var refundID string

		resp, httpRes, err := apiClient.RefundApi.GetRefund(context.Background(), refundID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RefundApiService GetAllRefunds", func(t *testing.T) {

		resp, httpRes, err := apiClient.RefundApi.GetAllRefunds(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RefundApiService CancelRefund", func(t *testing.T) {

		var refundID string

		resp, httpRes, err := apiClient.RefundApi.CancelRefund(context.Background(), refundID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
