/*
Payment Requests_test

Testing PaymentRequestApiService

*/

// Code generated by OpenAPI Generator

package xendit

import (
	"context"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	xendit "github.com/xendit/xendit-go/v3"
)

func Test_xendit_PaymentRequestApiService(t *testing.T) {

	apiKey := os.Getenv("XND_APIKEY")
	if apiKey == "" {
		t.Skip("XND_APIKEY not set")
	}
	
	apiClient := xendit.NewClient(apiKey)

	t.Run("Test PaymentRequestApiService CreatePaymentRequest", func(t *testing.T) {

		resp, httpRes, err := apiClient.PaymentRequestApi.CreatePaymentRequest(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentRequestApiService GetPaymentRequestByID", func(t *testing.T) {

		var paymentRequestId string

		resp, httpRes, err := apiClient.PaymentRequestApi.GetPaymentRequestByID(context.Background(), paymentRequestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentRequestApiService GetPaymentRequestCaptures", func(t *testing.T) {

		var paymentRequestId string

		resp, httpRes, err := apiClient.PaymentRequestApi.GetPaymentRequestCaptures(context.Background(), paymentRequestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentRequestApiService GetAllPaymentRequests", func(t *testing.T) {

		resp, httpRes, err := apiClient.PaymentRequestApi.GetAllPaymentRequests(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentRequestApiService CapturePaymentRequest", func(t *testing.T) {

		var paymentRequestId string

		resp, httpRes, err := apiClient.PaymentRequestApi.CapturePaymentRequest(context.Background(), paymentRequestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentRequestApiService AuthorizePaymentRequest", func(t *testing.T) {

		var paymentRequestId string

		resp, httpRes, err := apiClient.PaymentRequestApi.AuthorizePaymentRequest(context.Background(), paymentRequestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentRequestApiService ResendPaymentRequestAuth", func(t *testing.T) {

		var paymentRequestId string

		resp, httpRes, err := apiClient.PaymentRequestApi.ResendPaymentRequestAuth(context.Background(), paymentRequestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
