// Code generated by OpenAPI Generator; DO NOT EDIT.
package balance_and_transaction

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	
	common "github.com/xendit/xendit-go/v3/common"
	utils "github.com/xendit/xendit-go/v3/utils"
)


type BalanceApi interface {

	/*
	GetBalance Retrieves balances for a business, default to CASH type

	Retrieves balance for your business, defaults to CASH type

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetBalanceRequest
	*/
	GetBalance(ctx context.Context) ApiGetBalanceRequest

	// GetBalanceExecute executes the request
	//  @return Balance
	GetBalanceExecute(r ApiGetBalanceRequest) (*Balance, *http.Response, error)
}

// BalanceApiService BalanceApi service
type BalanceApiService struct {
	client common.IClient
}

// NewBalanceApi Create a new BalanceApi service
func NewBalanceApi (client common.IClient) BalanceApi {
	return &BalanceApiService{
		client: client,
	}
}


type ApiGetBalanceRequest struct {
	ctx context.Context
	ApiService BalanceApi
	accountType *string
	currency *string
	forUserId *string
}

// The selected balance type
func (r ApiGetBalanceRequest) AccountType(accountType string) ApiGetBalanceRequest {
	r.accountType = &accountType
	return r
}

// Currency for filter for customers with multi currency accounts
func (r ApiGetBalanceRequest) Currency(currency string) ApiGetBalanceRequest {
	r.currency = &currency
	return r
}

// The sub-account user-id that you want to make this transaction for. This header is only used if you have access to xenPlatform. See xenPlatform for more information
func (r ApiGetBalanceRequest) ForUserId(forUserId string) ApiGetBalanceRequest {
	r.forUserId = &forUserId
	return r
}

func (r ApiGetBalanceRequest) Execute() (*Balance, *http.Response, error) {
	return r.ApiService.GetBalanceExecute(r)
}

/*
GetBalance Retrieves balances for a business, default to CASH type

Retrieves balance for your business, defaults to CASH type

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetBalanceRequest
*/
func (a *BalanceApiService) GetBalance(ctx context.Context) ApiGetBalanceRequest {
	return ApiGetBalanceRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return Balance
func (a *BalanceApiService) GetBalanceExecute(r ApiGetBalanceRequest) (*Balance, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []common.FormFile
		localVarReturnValue  *Balance
	)

	localBasePath, err := a.client.GetConfig().ServerURLWithContext(r.ctx, "BalanceApiService.GetBalance")
	if err != nil {
		return localVarReturnValue, nil, common.NewGenericOpenAPIError(nil, err.Error(), nil)
	}

	localVarPath := localBasePath + "/balance"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.accountType != nil {
		utils.ParameterAddToHeaderOrQuery(localVarQueryParams, "account_type", r.accountType, "")
	}
	if r.currency != nil {
		utils.ParameterAddToHeaderOrQuery(localVarQueryParams, "currency", r.currency, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := utils.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := utils.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.forUserId != nil {
		utils.ParameterAddToHeaderOrQuery(localVarHeaderParams, "for-user-id", r.forUserId, "")
	}
	req, err := a.client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := common.NewGenericOpenAPIError(localVarBody, localVarHTTPResponse.Status, nil)
		if localVarHTTPResponse.StatusCode == 400 {
			var v ValidationError
			err = a.client.Decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.SetError(err.Error())
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.SetError(utils.FormatErrorMessage(localVarHTTPResponse.Status, &v))
					newErr.SetModel(v)
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
			var v ServerError
			err = a.client.Decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.SetError(err.Error())
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.SetError(utils.FormatErrorMessage(localVarHTTPResponse.Status, &v))
					newErr.SetModel(v)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := common.NewGenericOpenAPIError(localVarBody, err.Error(), nil)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
